definitions:
  handlers.healthResponse:
    properties:
      status:
        type: string
      uptime:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health:
    get:
      description: Returns the server health status along with version and uptime
      produces:
      - application/json
      responses:
        "200":
          description: Server is healthy
          schema:
            $ref: '#/definitions/handlers.healthResponse'
        "500":
          description: Health check failed
          schema:
            type: string
      summary: Health check
      tags:
      - Health
swagger: "2.0"
